### ISSUE TITLE
what critera do you base on to select  focal population?

### ISSUE THREAD

**Issue by dragonzhiqin** [spiritu-santi/Climate-Change-Genomics#1]
I have read your paper and then I found that you selected two focal populations(south2 and north4 ) to analyse gene flow.However I can't  find the critera which you use to define 'focal population'.I'm looking forward to you reply.

**Comment by spiritu-santi** [comment]
The selection was only to demonstrate our approach to analyze gene flow, but results are available for all populations.
These two populations where chosen based on the frequency of candidate SNPs and their assignment to populations clusters.

**Comment by dragonzhiqin** [comment]
thanks for your reply !!!
